ARG WP_VERSION
ARG PHP_VERSION
ARG DOCKER_REGISTRY

FROM wp-graphql-persisted-queries:latest-wp${WP_VERSION}-php${PHP_VERSION}

FROM ${DOCKER_REGISTRY:-}wp-graphql-testing:latest-wp${WP_VERSION}-php${PHP_VERSION}

ENV PROJECT_DIR="${PLUGINS_DIR}/wp-graphql-persisted-queries"

RUN echo "pcov.directory = /var/www/html/wp-content/plugins/wp-graphql-persisted-queries" >> /usr/local/etc/php/conf.d/docker-php-ext-pcov.ini
