name: Deploy to WordPress.org
on:
  release:
    types: [ published ]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          tools: composer

      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Install PHP dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wpgraphql-smart-cache
          ASSETS_DIR: .wordpress-org
